- name: Deploy to Cloudflare Workers
        run: |
          mkdir -p /tmp/site
          git archive HEAD | tar -x -C /tmp/site
          cd /tmp/site
          wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
